In [1]:
import numpy as np

arr1 = np.array([10, 20, 30])

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

combined = np.vstack((arr2, arr1))

print("1D Array:")
print(arr1)

print("\n2D Array:")
print(arr2)

print("\nCombined Array:")
print(combined)

1D Array:
[10 20 30]

2D Array:
[[1 2 3]
 [4 5 6]]

Combined Array:
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


In [3]:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original Array:")
print(arr)

print("\nFlattened Array:")
print(arr.flatten())

Original Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:
[1 2 3 4 5 6]


In [4]:

arr = np.array([10, 20, 30, 40, 50])

print("Original Array:", arr)
print("Reversed Array:", arr[::-1])

Original Array: [10 20 30 40 50]
Reversed Array: [50 40 30 20 10]


In [6]:

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr)

print("Maximum Value:", np.max(arr))
print("Minimum Value:", np.min(arr))

print("Rows:", arr.shape[0])
print("Columns:", arr.shape[1])

print("Element at row 1 column 2:", arr[1][2])

total = 0
for row in arr:
    for item in row:
        total += item

print("Sum:", total)

[[10 20 30]
 [40 50 60]]
Maximum Value: 60
Minimum Value: 10
Rows: 2
Columns: 3
Element at row 1 column 2: 60
Sum: 210


In [7]:

arr = np.arange(24).reshape(2, 3, 4)

print("3D Array:")
print(arr)

print("\nUsing Nested For Loop")

for matrix in arr:
    for row in matrix:
        for item in row:
            print(item, end=" ")
print()

print("\nUsing nditer")

for item in np.nditer(arr):
    print(item, end=" ")

3D Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Using Nested For Loop
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

Using nditer
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [8]:
import numpy as np
from statistics import mode

arr1 = np.array([
    [3, 4],
    [5, 6]
])

arr2 = np.array([
    [1, 0],
    [7, 8]
])

avg = (arr1 + arr2) / 2

print("Average Array:")
print(avg)

combined = np.concatenate((arr1.flatten(), arr2.flatten()))

print("Mean:", np.mean(combined))
print("Median:", np.median(combined))
print("Mode:", mode(combined))

Average Array:
[[2. 2.]
 [6. 7.]]
Mean: 4.25
Median: 4.5
Mode: 3
