In [1]:
import numpy as np

arr = np.array([
    [6, -8, 73, -110],
    [np.nan, -8, 0, 94]
])

print("Original Array:")
print(arr)


arr = np.nan_to_num(arr, nan=0)

print("\nNaN Replaced with 0:")
print(arr)


transpose = arr.T

print("\nTranspose:")
print(transpose)

Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

NaN Replaced with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

Transpose:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [ ]:

arr = np.arange(24).reshape(2, 3, 4)

print("Original Shape:")
print(arr.shape)

new_arr = np.moveaxis(arr, 0, 2)

print("New Shape:")
print(new_arr.shape)

print(new_arr)

Original Shape:
(2, 3, 4)
New Shape:
(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [3]:

arr = np.array([
    [10, np.nan, 30],
    [20, 25, np.nan],
    [30, 35, 50]
])

print("Original Array:")
print(arr)

col_mean = np.nanmean(arr, axis=0)

indices = np.where(np.isnan(arr))

arr[indices] = np.take(col_mean, indices[1])

print("\nAfter Replacing NaN:")
print(arr)

Original Array:
[[10. nan 30.]
 [20. 25. nan]
 [30. 35. 50.]]

After Replacing NaN:
[[10. 30. 30.]
 [20. 25. 40.]
 [30. 35. 50.]]


In [4]:

arr = np.array([
    [10, -5, 20],
    [-8, 30, -12],
    [15, -4, 25]
])

print("Original Array:")
print(arr)

arr[arr < 0] = 0

print("\nAfter Replacing Negative Values:")
print(arr)

Original Array:
[[ 10  -5  20]
 [ -8  30 -12]
 [ 15  -4  25]]

After Replacing Negative Values:
[[10  0 20]
 [ 0 30  0]
 [15  0 25]]
