In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize)

Array: [10 20 30 40 50]
Shape: (5,)
Dimension: 1
Data Type: int64
Item Size: 8


In [2]:

arr = np.array([1, 2, 3, 4, 5, 6])

arr2d = arr.reshape(2, 3)

print(arr2d)

[[1 2 3]
 [4 5 6]]


In [3]:

arr = np.full((3, 3), 9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [4]:

arr = np.linspace(25, 125, 10)
print(arr)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [5]:

lst = [5, 10, 15, 20]
arr = np.array(lst)
print(arr)

[ 5 10 15 20]


In [6]:

arr = np.array([10, 20, 30, 40, 50])

print("Original:", arr)
print("Reversed:", arr[::-1])

Original: [10 20 30 40 50]
Reversed: [50 40 30 20 10]


In [7]:

arr = np.arange(48).reshape(4, 4, 3)

print(arr)

print("\nRequired Value:")
print(arr[1, 0, 2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

Required Value:
14


In [8]:

arr = np.arange(1, 17).reshape(4, 4)

print("Original Array:")
print(arr)

result = arr[::2, 1::2]

print("\nOdd Rows and Even Columns:")
print(result)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows and Even Columns:
[[ 2  4]
 [10 12]]


In [9]:

arr = np.arange(48).reshape(4, 4, 3)

result = arr[1, :2, :2]
print(result)

[[12 13]
 [15 16]]


In [10]:

arr = np.array([
    [23, 56, 78, 93],
    [71, 82, 13, 24]
])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1

print(arr)

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [11]:

arr = np.array([1, 0, 2, 0, 3, 0, 4])

indices = np.nonzero(arr)
print(indices)

(array([0, 2, 4, 6]),)


In [12]:

arr1 = np.array([10, 20, 30])
arr2 = np.array([5, 15, 25])

print("Addition:")
print(arr1 + arr2)

print("Multiplication:")
print(arr1 * arr2)

Addition:
[15 35 55]
Multiplication:
[ 50 300 750]


In [13]:

arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)

print("Dot Product =", dot_product)

Dot Product = 1875
